Make edgex-ekuiper aware security is on or off
canonical/edgex-ekuiper-snap pull request #20
Opened 2022-04-07 17:44 UTC by MonicaisHer

close: https://github.com/canonical/edgex-ekuiper-snap/issues/18

2022-04-07 19:00 UTC, farshidtz requested changes
Thanks for the addition. It should do the job but in a very complicated way. The added go app increases the size of the snap but it's doing anything.

2022-04-08 09:06 UTC, farshidtz commented on snap/hooks/configure
> +fi
@MonicaisHer I added some validation which I have not tested. Please check.

2022-04-08 09:35 UTC, MonicaisHer commented on snap/hooks/configure
> +fi
This works:
```
if [ "$EDGEX_SECURITY" == "" ] ; then
  :
elif [ "$EDGEX_SECURITY" != "off" ] && [ "$EDGEX_SECURITY" != "on" ] ; then
	logger --stderr "$LOG_PREFIX: edgex-security can only be set to either 'on' or 'off'. When unset, it defaults to 'on'"
  exit 1
fi
```

2022-04-08 10:24 UTC, farshidtz approved these changes
Thanks @MonicaisHer. It looks good. I've created the issue #21 to discuss how we can make this more configurable.

2022-04-08 12:09 UTC, merged