Set ekuiper to subscribe to raw edge events by default
canonical/edgex-ekuiper-snap pull request #34
Opened 2022-10-13 17:22 UTC by MonicaisHer

2022-10-13 20:54 UTC, farshidtz commented on snap/local/runtime-helpers/bin/service-config-overrides.sh
> +fi
OR when unset, because we wanna default to use ASC events.

2022-10-13 20:54 UTC, farshidtz commented on snap/snapcraft.yaml
> +      EDGEX__DEFAULT__MESSAGETYPE: request
Better if these come from the configuration file. Otherwise it won't allow any other user-defined values.

2022-10-14 13:21 UTC, farshidtz commented on snap/hooks/configure
> +    logger --stderr "$LOG_PREFIX: source must be either 'app-service-configurable' or ''. When unset, it defaults to '' using edgex message bus"
```suggestion
    logger --stderr "$LOG_PREFIX: invalid source value: '$SOURCE'. The only supported value is 'app-service-configurable' to override default.topic to 'rules-events' and default.messageType to 'event', to subscribe to events filtered by EdgeX App Service Configurable.

2022-10-14 13:22 UTC, farshidtz commented on snap/snapcraft.yaml
> +    install-mode: disable
This change should ve reflected in tests and docs.

2022-10-14 13:25 UTC, farshidtz commented on README.md
> +There are two types of EdgeX events sources: EdgeX(default) and app-service-configurable.
A little misleading. This sentence can be removed since it is explained better below.

2022-10-14 13:26 UTC, farshidtz commented on README.md
> +Instead of subscribing to subscribe to all EdgeX events, eKuiper can be configured to subscribe to events filtered by App Service Configurable.
```suggestion
Instead of subscribing to all EdgeX events, eKuiper can be configured to subscribe to events filtered by EdgeX App Service Configurable.
```

2022-10-14 13:28 UTC, farshidtz commented on README.md
> +To do so, install edgex-app-service-configurable, and set profile to `rule-engine`:
```suggestion
To do so, install [edgex-app-service-configurable](https://snapcraft.io/edgex-app-service-configurable), and set its profile to `rule-engine`:
```

2022-10-14 13:29 UTC, farshidtz commented on README.md
> +set eKuiper's source to `app-service-cofigurable`:
```suggestion
Then, set eKuiper's source to `app-service-configurable`:
```

2022-10-17 13:28 UTC, farshidtz commented on README.md
>  edgex-ekuiper.kuiper                                     enabled   active    -
There is some conflicting information here. The service is disabled and not started by default, and not so via the commands given. However, the services command (line 71) shows eKuiper is enabled and active.

There could be a command to enable and start ekuiper after line 61, but this isn't enough. There is currently no way to start eKuiper using a gadget for preloading an Ubuntu Core image with enabled eKuiper.

2022-10-17 13:30 UTC, farshidtz commented on README.md
> +# start the service to pick up the changes made to the config file
> # start the service to pick up the changes made to the config file

There are no changes made to config files.

2022-10-21 07:05 UTC, MonicaisHer commented
Test result from () using snap from channel edge/pr-34:
```
:~/Desktop/edgex513/edgex-snap-testing$ go test -p 1 -v ./test/suites/ekuiper/
2022/10/21 09:01:46 [CLEAN]
2022/10/21 09:01:46 [exec] sudo snap remove --purge edgex-ekuiper
[sudo] password for mengyi: 
2022/10/21 09:01:53 [stdout] edgex-ekuiper removed
2022/10/21 09:01:53 [exec] sudo snap remove --purge edgexfoundry
2022/10/21 09:01:55 [stdout] 2022-10-21T09:01:54+02:00 INFO Waiting for "snap.edgexfoundry.core-data.service" to stop.
2022/10/21 09:01:56 [stdout] 2022-10-21T09:01:56+02:00 INFO Waiting for "snap.edgexfoundry.core-metadata.service" to stop.
2022/10/21 09:02:01 [stdout] edgexfoundry removed
2022/10/21 09:02:01 [exec] sudo snap remove --purge edgex-device-virtual
2022/10/21 09:02:01 [stderr] snap "edgex-device-virtual" is not installed
2022/10/21 09:02:01 [SETUP]
2022/10/21 09:02:01 [exec] sudo snap install edgex-ekuiper --channel=edge/pr-34
2022/10/21 09:02:07 [stdout] edgex-ekuiper (edge/pr-34) 1.5.1+snap+git14.b5a77e4-dirty from Canonical** installed
2022/10/21 09:02:07 [exec] sudo snap install edgexfoundry --channel=latest/edge
2022/10/21 09:02:50 [stdout] edgexfoundry (edge) 2.3.0-dev.96 from Canonical** installed
2022/10/21 09:02:50 [exec] sudo snap install edgex-device-virtual --channel=latest/edge
2022/10/21 09:02:55 [stdout] edgex-device-virtual (edge) 2.3.0-dev.25 from Canonical** installed
2022/10/21 09:02:55 Retry 1/180: Waiting for ports: 59880 (core-data), 59881 (core-metadata), 59882 (core-command), 8200 (vault), 8500 (consul), 5432 (kong-database), 6379 (redis), 8000 (kong)
=== RUN   TestCommon
=== RUN   TestCommon/content_interfaces
=== RUN   TestCommon/content_interfaces/seed_secretstore_token
    exec.go:19: [exec] sudo cat /var/snap/edgexfoundry/current/secrets/edgex-ekuiper/secrets-token.json
    exec.go:19: [exec] sudo cat /var/snap/edgex-ekuiper/current/edgex-ekuiper/secrets-token.json
=== RUN   TestCommon/net
    exec.go:19: [exec] sudo snap start edgex-ekuiper
    exec.go:93: [stdout] Started.
=== RUN   TestCommon/net/ports_open
    net.go:140: Retry 1/60: Waiting for ports: 20498 (ekuiper), 59720 (ekuiper/rest-api)
=== CONT  TestCommon/net
    net.go:140: Retry 1/60: Waiting for ports: 20498 (ekuiper), 59720 (ekuiper/rest-api)
=== RUN   TestCommon/net/ports_not_listening_on_all_interfaces
    exec.go:19: [exec] sudo lsof -nPi :20498 || true
    net.go:260: Looking for '*:20498 (LISTEN)'
    exec.go:19: [exec] sudo lsof -nPi :59720 || true
    net.go:260: Looking for '*:59720 (LISTEN)'
=== RUN   TestCommon/net/ports_listening_on_localhost
    exec.go:19: [exec] sudo lsof -nPi :20498 || true
    net.go:260: Looking for '127.0.0.1:20498 (LISTEN)'
    exec.go:19: [exec] sudo lsof -nPi :59720 || true
    net.go:260: Looking for '127.0.0.1:59720 (LISTEN)'
=== CONT  TestCommon/net
    exec.go:19: [exec] sudo snap stop edgex-ekuiper
    exec.go:93: [stdout] 2022-10-21T09:02:57+02:00 INFO Waiting for "snap.edgex-ekuiper.kuiper.service" to stop.
    exec.go:93: [stdout] Stopped.
=== RUN   TestCommon/packaging
=== RUN   TestCommon/packaging/semantic_snap_version
    exec.go:19: [exec] snap info edgex-ekuiper | grep installed | awk '{print $2}'
    exec.go:93: [stdout] 1.5.1+snap+git14.b5a77e4-dirty
--- PASS: TestCommon (6.67s)
    --- PASS: TestCommon/content_interfaces (0.01s)
        --- PASS: TestCommon/content_interfaces/seed_secretstore_token (0.01s)
    --- PASS: TestCommon/net (6.42s)
        --- PASS: TestCommon/net/ports_open (0.00s)
        --- PASS: TestCommon/net/ports_not_listening_on_all_interfaces (0.29s)
        --- PASS: TestCommon/net/ports_listening_on_localhost (0.28s)
    --- PASS: TestCommon/packaging (0.24s)
        --- PASS: TestCommon/packaging/semantic_snap_version (0.24s)
=== RUN   TestStreamsAndRules
    exec.go:19: [exec] sudo snap start edgex-ekuiper.kuiper
    exec.go:93: [stdout] Started.
    exec.go:19: [exec] sudo snap start edgex-device-virtual
    exec.go:93: [stdout] Started.
=== RUN   TestStreamsAndRules/create_stream
    exec.go:19: [exec] edgex-ekuiper.kuiper-cli create stream stream1 '()WITH(FORMAT="JSON",TYPE="edgex")'
=== RUN   TestStreamsAndRules/create_rule_log
    exec.go:19: [exec] edgex-ekuiper.kuiper-cli create rule rule_log '
                                {
                                        "sql":"SELECT * from stream1",
                                        "actions":[
                                                {
                                                        "log":{}
                                                }
                                        ]
                                }'
=== RUN   TestStreamsAndRules/create_rule_edgex_message_bus
    exec.go:19: [exec] edgex-ekuiper.kuiper-cli create rule rule_edgex_message_bus '
                                {
                                   "sql":"SELECT * from stream1",
                                   "actions": [
                                          {
                                                 "edgex": {
                                                        "connectionSelector": "edgex.redisMsgBus",
                                                        "topicPrefix": "edgex/events/device", 
                                                        "messageType": "request",
                                                        "deviceName": "device-test"
                                                 }
                                          }
                                   ]
                                }'
=== CONT  TestStreamsAndRules
    net.go:140: Retry 1/60: Waiting for ports: 59900 (device-virtual)
    net.go:140: Retry 2/60: Waiting for ports: 59900 (device-virtual)
waiting for device-virtual produce readings, current retry count: 1/60
waiting for device-virtual produce readings, current retry count: 2/60
waiting for device-virtual produce readings, current retry count: 3/60
waiting for device-virtual produce readings, current retry count: 4/60
waiting for device-virtual produce readings, current retry count: 5/60
waiting for device-virtual produce readings, current retry count: 6/60
waiting for device-virtual produce readings, current retry count: 7/60
waiting for device-virtual produce readings, current retry count: 8/60
waiting for device-virtual produce readings, current retry count: 9/60
waiting for device-virtual produce readings, current retry count: 10/60
device-virtual is producing readings now
=== RUN   TestStreamsAndRules/check_rule_log
    exec.go:19: [exec] edgex-ekuiper.kuiper-cli getstatus rule rule_log
=== RUN   TestStreamsAndRules/check_rule_edgex_message_bus
    exec.go:19: [exec] edgex-ekuiper.kuiper-cli getstatus rule rule_edgex_message_bus
=== CONT  TestStreamsAndRules
    exec.go:19: [exec] sudo snap stop edgex-ekuiper.kuiper
    exec.go:93: [stdout] Stopped.
    exec.go:19: [exec] sudo snap stop edgex-device-virtual
    exec.go:93: [stdout] Stopped.
--- PASS: TestStreamsAndRules (12.19s)
    --- PASS: TestStreamsAndRules/create_stream (0.04s)
    --- PASS: TestStreamsAndRules/create_rule_log (0.05s)
    --- PASS: TestStreamsAndRules/create_rule_edgex_message_bus (0.05s)
    --- PASS: TestStreamsAndRules/check_rule_log (0.04s)
    --- PASS: TestStreamsAndRules/check_rule_edgex_message_bus (0.04s)
PASS
2022/10/21 09:03:14 [TEARDOWN]
2022/10/21 09:03:14 [exec] (sudo journalctl --since "2022-10-21 09:02:01" --no-pager | grep "edgex-ekuiper"|| true) > edgex-ekuiper.log
Wrote snap logs to /home/mengyi/Desktop/edgex513/edgex-snap-testing/test/suites/ekuiper/edgex-ekuiper.log
2022/10/21 09:03:14 [exec] (sudo journalctl --since "2022-10-21 09:02:01" --no-pager | grep "edgexfoundry"|| true) > edgexfoundry.log
Wrote snap logs to /home/mengyi/Desktop/edgex513/edgex-snap-testing/test/suites/ekuiper/edgexfoundry.log
2022/10/21 09:03:14 [exec] (sudo journalctl --since "2022-10-21 09:02:01" --no-pager | grep "edgex-device-virtual"|| true) > edgex-device-virtual.log
Wrote snap logs to  [...]

2022-10-21 07:14 UTC, MonicaisHer commented on snap/local/helper-go/go.mod
> +require github.com/canonical/edgex-snap-hooks/v2 v2.4.2-0.20221020131353-9f5a8f96ce28
todo: Update hooks when latest version is available

2022-10-21 08:16 UTC, farshidtz commented on snap/hooks/configure
> -fi
We can now drop the support for edgex-security option and use the `edgex-security-secret-store` config option to be consistent with other EdgeX services. This will need minor modifications to redis credentials query script and the README.

2022-10-21 08:19 UTC, farshidtz commented on snap/local/helper-go/configure.go
> +	options.SetSegmentSeparator("_")
```suggestion
	log.Info("Setting config hierarchy separator to __")
	options.SetHierarchySeparator("__")
	log.Info("Setting config segment separator to _")
	options.SetSegmentSeparator("_")
```

2022-10-21 08:27 UTC, farshidtz commented on snap/hooks/connect-slot-edgex-secretstore-token
> -
Added an issue to document the secret interface in README: https://github.com/canonical/edgex-ekuiper-snap/issues/36

2022-10-21 09:16 UTC, farshidtz commented on snap/local/helper-go/go.mod
> +require github.com/canonical/edgex-snap-hooks/v2 v2.4.2-0.20221020131353-9f5a8f96ce28
It has been released.

2022-10-21 12:39 UTC, MonicaisHer commented
Test result from https://github.com/canonical/edgex-snap-testing/pull/125 using snap from channel edge/pr-34:
```
:37:29 [exec] sudo snap remove --purge edgexfoundry
2022/10/21 14:37:29 [stderr] snap "edgexfoundry" is not installed
2022/10/21 14:37:29 [exec] sudo snap remove --purge edgex-device-virtual
2022/10/21 14:37:29 [stderr] snap "edgex-device-virtual" is not installed
2022/10/21 14:37:29 [SETUP]
2022/10/21 14:37:29 [exec] sudo snap install edgex-ekuiper --channel=edge/pr-34
2022/10/21 14:37:35 [stdout] edgex-ekuiper (edge/pr-34) 1.5.1+snap+git19.90e89da-dirty from Canonical** installed
2022/10/21 14:37:35 [exec] sudo snap install edgexfoundry --channel=latest/edge
2022/10/21 14:38:19 [stdout] edgexfoundry (edge) 2.3.0-dev.96 from Canonical** installed
2022/10/21 14:38:19 [exec] sudo snap install edgex-device-virtual --channel=latest/edge
2022/10/21 14:38:24 [stdout] edgex-device-virtual (edge) 2.3.0-dev.25 from Canonical** installed
2022/10/21 14:38:24 Retry 1/180: Waiting for ports: 59880 (core-data), 59881 (core-metadata), 59882 (core-command), 8200 (vault), 8500 (consul), 5432 (kong-database), 6379 (redis), 8000 (kong)
=== RUN   TestCommon
=== RUN   TestCommon/content_interfaces
=== RUN   TestCommon/content_interfaces/seed_secretstore_token
    exec.go:19: [exec] sudo cat /var/snap/edgexfoundry/current/secrets/edgex-ekuiper/secrets-token.json
    exec.go:19: [exec] sudo cat /var/snap/edgex-ekuiper/current/edgex-ekuiper/secrets-token.json
=== RUN   TestCommon/net
    exec.go:19: [exec] sudo snap start edgex-ekuiper
    exec.go:93: [stdout] Started.
=== RUN   TestCommon/net/ports_open
    net.go:140: Retry 1/60: Waiting for ports: 20498 (ekuiper), 59720 (ekuiper/rest-api)
=== CONT  TestCommon/net
    net.go:140: Retry 1/60: Waiting for ports: 20498 (ekuiper), 59720 (ekuiper/rest-api)
=== RUN   TestCommon/net/ports_not_listening_on_all_interfaces
    exec.go:19: [exec] sudo lsof -nPi :20498 || true
    net.go:260: Looking for '*:20498 (LISTEN)'
    exec.go:19: [exec] sudo lsof -nPi :59720 || true
    net.go:260: Looking for '*:59720 (LISTEN)'
=== RUN   TestCommon/net/ports_listening_on_localhost
    exec.go:19: [exec] sudo lsof -nPi :20498 || true
    net.go:260: Looking for '127.0.0.1:20498 (LISTEN)'
    exec.go:19: [exec] sudo lsof -nPi :59720 || true
    net.go:260: Looking for '127.0.0.1:59720 (LISTEN)'
=== CONT  TestCommon/net
    exec.go:19: [exec] sudo snap stop edgex-ekuiper
    exec.go:93: [stdout] 2022-10-21T14:38:26+02:00 INFO Waiting for "snap.edgex-ekuiper.kuiper.service" to stop.
    exec.go:93: [stdout] Stopped.
=== RUN   TestCommon/packaging
=== RUN   TestCommon/packaging/semantic_snap_version
    exec.go:19: [exec] snap info edgex-ekuiper | grep installed | awk '{print $2}'
    exec.go:93: [stdout] 1.5.1+snap+git19.90e89da-dirty
--- PASS: TestCommon (7.15s)
    --- PASS: TestCommon/content_interfaces (0.01s)
        --- PASS: TestCommon/content_interfaces/seed_secretstore_token (0.01s)
    --- PASS: TestCommon/net (6.87s)
        --- PASS: TestCommon/net/ports_open (0.00s)
        --- PASS: TestCommon/net/ports_not_listening_on_all_interfaces (0.28s)
        --- PASS: TestCommon/net/ports_listening_on_localhost (0.27s)
    --- PASS: TestCommon/packaging (0.27s)
        --- PASS: TestCommon/packaging/semantic_snap_version (0.27s)
=== RUN   TestStreamsAndRules
    exec.go:19: [exec] sudo snap start edgex-ekuiper.kuiper
    exec.go:93: [stdout] Started.
    exec.go:19: [exec] sudo snap start edgex-device-virtual
    exec.go:93: [stdout] Started.
=== RUN   TestStreamsAndRules/create_stream
    exec.go:19: [exec] edgex-ekuiper.kuiper-cli create stream stream1 '()WITH(FORMAT="JSON",TYPE="edgex")'
=== RUN   TestStreamsAndRules/create_rule_log
    exec.go:19: [exec] edgex-ekuiper.kuiper-cli create rule rule_log '
                                {
                                        "sql":"SELECT * from stream1",
                                        "actions":[
                                                {
                                                        "log":{}
                                                }
                                        ]
                                }'
=== RUN   TestStreamsAndRules/create_rule_edgex_message_bus
    exec.go:19: [exec] edgex-ekuiper.kuiper-cli create rule rule_edgex_message_bus '
                                {
                                   "sql":"SELECT * from stream1",
                                   "actions": [
                                          {
                                                 "edgex": {
                                                        "connectionSelector": "edgex.redisMsgBus",
                                                        "topicPrefix": "edgex/events/device", 
                                                        "messageType": "request",
                                                        "deviceName": "device-test"
                                                 }
                                          }
                                   ]
                                }'
=== CONT  TestStreamsAndRules
    net.go:140: Retry 1/60: Waiting for ports: 59900 (device-virtual)
    net.go:140: Retry 2/60: Waiting for ports: 59900 (device-virtual)
=== RUN   TestStreamsAndRules/query_readings
    readings.go:45: waiting for device-virtual produce readings, current retry count: 1/60
    readings.go:45: waiting for device-virtual produce readings, current retry count: 2/60
    readings.go:45: waiting for device-virtual produce readings, current retry count: 3/60
    readings.go:45: waiting for device-virtual produce readings, current retry count: 4/60
    readings.go:45: waiting for device-virtual produce readings, current retry count: 5/60
    readings.go:45: waiting for device-virtual produce readings, current retry count: 6/60
    readings.go:45: waiting for device-virtual produce readings, current retry count: 7/60
    readings.go:45: waiting for device-virtual produce readings, current retry count: 8/60
    readings.go:45: waiting for device-virtual produce readings, current retry count: 9/60
    readings.go:45: waiting for device-virtual produce readings, current retry count: 10/60
    readings.go:48: device-virtual is producing readings now, readings queried from core-data
=== RUN   TestStreamsAndRules/check_rule_log
    exec.go:19: [exec] sudo journalctl --since "2022-10-21 14:38:43" --no-pager | grep "edgex-ekuiper"|| true
=== RUN   TestStreamsAndRules/check_rule_edgex_message_bus
    net.go:140: Retry 1/60: Waiting for ports: 59900 (device-virtual)
=== CONT  TestStreamsAndRules
    exec.go:19: [exec] sudo snap stop edgex-ekuiper.kuiper
    exec.go:93: [stdout] Stopped.
    exec.go:19: [exec] sudo snap stop edgex-device-virtual
    exec.go:93: [stdout] 2022-10-21T14:38:47+02:00 INFO Waiting for "snap.edgex-device-virtual.device-virtual.service" to stop.
    exec.go:93: [stdout] Stopped.
--- PASS: TestStreamsAndRules (19.57s)
    --- PASS: TestStreamsAndRules/create_stream (0.04s)
    --- PASS: TestStreamsAndRules/create_rule_log (0.05s)
    --- PASS: TestStreamsAndRules/create_rule_edgex_message_bus (0.05s)
    --- PASS: TestStreamsAndRules/query_readings (10.01s)
    --- PASS: TestStreamsAndRules/check_rule_log (2.67s)
    --- PASS: TestStreamsAndRules/check_rule_edgex_message_bus (0.00s)
PASS
2022/10/21 14:38:51 [TEARDOWN]
2022/10/21 14:38:51 [exec] (sudo journalctl --since "2022-10-21 14:37:29" --no-pager | grep "edgex-ekuiper"|| true) > edgex-ekuiper.log
Wrote snap logs to /home/mengyi/Desktop/edgex513/edgex-snap-testing/test/suites/ekuiper/edgex-ekuiper.log
2022/10/21 14:38:51 [exec] (sudo journalctl --since "2022-10-21 14:37:29" --no-pager | grep "edgexfoundry"|| true) > edgexfoundry.log
Wrote snap logs to /home/mengyi/Desktop/edgex513/edgex-snap-testing/test/suites/ekuiper/edgexfoundry.log
2022/10/21 14:38:51 [exec] (sudo journalctl --since "2022-10-21 14:37:29" --no-pager | grep "edgex-de [...]

2022-10-21 14:12 UTC, farshidtz commented on README.md
>  edgex-ekuiper.kuiper                                     enabled   active    -
Set to unresolved as there are no instructions for starting ekuiper, but the services command shows it as started.

2022-10-21 14:17 UTC, farshidtz requested changes

2022-10-21 14:17 UTC, farshidtz commented on snap/local/bin/source-env-file.sh
> +# binary name == service name/key
unused code

2022-10-21 14:17 UTC, farshidtz commented on snap/local/helper-go/install.go
> +		log.Fatalf("Error installing config file: %s", err)
```suggestion
		log.Fatalf("Error installing config files: %s", err)
```

2022-10-21 14:17 UTC, farshidtz commented on snap/local/helper-go/configure.go
> +	}
Why is this needed?

2022-10-24 10:14 UTC, MonicaisHer commented on snap/local/helper-go/configure.go
> -		log.Fatalf("edgex-security-secret-store must be either 'true' or 'false'. When unset, it defaults to 'true'")
Should there be a warning if the config option is invalid? e.g. 
```
snap set edgex-ekuiper config.edgex-security-secret-store=bad
```

2022-10-24 10:20 UTC, farshidtz commented on snap/local/helper-go/configure.go
> -		log.Fatalf("edgex-security-secret-store must be either 'true' or 'false'. When unset, it defaults to 'true'")
There is no warning for any other `config.` setting in this and other EdgeX snaps because these often lead to dumping strings in a file. I think the logging in setup-redis-credentials.sh is sufficient for debugging purposes. You can nevertheless add back the validation if you think it is useful.

2022-10-24 10:26 UTC, MonicaisHer commented on snap/local/helper-go/configure.go
> -		log.Fatalf("edgex-security-secret-store must be either 'true' or 'false'. When unset, it defaults to 'true'")
Thanks. No, it is unnecessary, and better to behave the same as other device/app services

2022-10-24 13:22 UTC, farshidtz commented
eKuiper tests from a local build pass:
```
LOCAL_SNAP=edgex-ekuiper_1.5.1+snap+git24.1a20ffa_amd64.snap go test -v -timeout 20m ./test/suites/ekuiper
2022/10/24 15:08:03 [CLEAN]
2022/10/24 15:08:03 [exec] sudo snap remove --purge edgex-ekuiper
2022/10/24 15:08:12 [stdout] edgex-ekuiper removed
2022/10/24 15:08:12 [exec] sudo snap remove --purge edgexfoundry
2022/10/24 15:08:13 [stdout] 2022-10-24T15:08:13+02:00 INFO Waiting for "snap.edgexfoundry.consul.service" to stop.
2022/10/24 15:08:15 [stdout] 2022-10-24T15:08:15+02:00 INFO Waiting for "snap.edgexfoundry.postgres.service" to stop.
2022/10/24 15:08:18 [stdout] 2022-10-24T15:08:18+02:00 INFO Waiting for "snap.edgexfoundry.kong-daemon.service" to stop.
2022/10/24 15:08:19 [stdout] 2022-10-24T15:08:19+02:00 INFO Waiting for "snap.edgexfoundry.core-metadata.service" to stop.
2022/10/24 15:08:20 [stdout] 2022-10-24T15:08:20+02:00 INFO Waiting for "snap.edgexfoundry.core-data.service" to stop.
2022/10/24 15:08:34 [stdout] edgexfoundry removed
2022/10/24 15:08:34 [exec] sudo snap remove --purge edgex-device-virtual
2022/10/24 15:08:36 [stdout] edgex-device-virtual removed
2022/10/24 15:08:36 [SETUP]
2022/10/24 15:08:36 [exec] sudo snap install --dangerous /home/farshid/projects/edgex/edgex-ekuiper-snap/edgex-ekuiper_1.5.1+snap+git24.1a20ffa_amd64.snap
2022/10/24 15:08:41 [stdout] edgex-ekuiper 1.5.1+snap+git24.1a20ffa installed
2022/10/24 15:08:41 [exec] sudo snap install edgexfoundry --channel=latest/edge
2022/10/24 15:10:04 [stdout] edgexfoundry (edge) 2.3.0-dev.99 from Canonical** installed
2022/10/24 15:10:04 [exec] sudo snap install edgex-device-virtual --channel=latest/edge
2022/10/24 15:10:13 [stdout] edgex-device-virtual (edge) 2.3.0-dev.25 from Canonical** installed
2022/10/24 15:10:13 [exec] sudo snap connect edgexfoundry:edgex-secretstore-token edgex-ekuiper:edgex-secretstore-token
2022/10/24 15:10:18 Retry 1/180: Waiting for ports: 59880 (core-data), 59881 (core-metadata), 59882 (core-command), 8200 (vault), 8500 (consul), 5432 (kong-database), 6379 (redis), 8000 (kong)
=== RUN   TestCommon
=== RUN   TestCommon/content_interfaces
=== RUN   TestCommon/content_interfaces/seed_secretstore_token
    exec.go:19: [exec] sudo cat /var/snap/edgexfoundry/current/secrets/edgex-ekuiper/secrets-token.json
    exec.go:19: [exec] sudo cat /var/snap/edgex-ekuiper/current/edgex-ekuiper/secrets-token.json
=== RUN   TestCommon/net
    exec.go:19: [exec] sudo snap start edgex-ekuiper
    exec.go:93: [stdout] Started.
=== RUN   TestCommon/net/ports_open
    net.go:140: Retry 1/60: Waiting for ports: 20498 (ekuiper), 59720 (ekuiper/rest-api)
    net.go:140: Retry 2/60: Waiting for ports: 20498 (ekuiper), 59720 (ekuiper/rest-api)
=== CONT  TestCommon/net
    net.go:140: Retry 1/60: Waiting for ports: 20498 (ekuiper), 59720 (ekuiper/rest-api)
=== RUN   TestCommon/net/ports_not_listening_on_all_interfaces
    exec.go:19: [exec] sudo lsof -nPi :20498 || true
    net.go:260: Looking for '*:20498 (LISTEN)'
    exec.go:19: [exec] sudo lsof -nPi :59720 || true
    net.go:260: Looking for '*:59720 (LISTEN)'
=== RUN   TestCommon/net/ports_listening_on_localhost
    exec.go:19: [exec] sudo lsof -nPi :20498 || true
    net.go:260: Looking for '127.0.0.1:20498 (LISTEN)'
    exec.go:19: [exec] sudo lsof -nPi :59720 || true
    net.go:260: Looking for '127.0.0.1:59720 (LISTEN)'
=== CONT  TestCommon/net
    exec.go:19: [exec] sudo snap stop edgex-ekuiper
    exec.go:93: [stdout] 2022-10-24T15:10:21+02:00 INFO Waiting for "snap.edgex-ekuiper.kuiper.service" to stop.
    exec.go:93: [stdout] Stopped.
=== RUN   TestCommon/packaging
=== RUN   TestCommon/packaging/semantic_snap_version
    exec.go:19: [exec] snap info edgex-ekuiper | grep installed | awk '{print $2}'
    exec.go:93: [stdout] 1.5.1+snap+git24.1a20ffa
--- PASS: TestCommon (6.87s)
    --- PASS: TestCommon/content_interfaces (0.03s)
        --- PASS: TestCommon/content_interfaces/seed_secretstore_token (0.03s)
    --- PASS: TestCommon/net (6.59s)
        --- PASS: TestCommon/net/ports_open (1.00s)
        --- PASS: TestCommon/net/ports_not_listening_on_all_interfaces (0.23s)
        --- PASS: TestCommon/net/ports_listening_on_localhost (0.23s)
    --- PASS: TestCommon/packaging (0.26s)
        --- PASS: TestCommon/packaging/semantic_snap_version (0.26s)
=== RUN   TestStreamsAndRules
    exec.go:19: [exec] sudo snap start edgex-ekuiper.kuiper
    exec.go:93: [stdout] Started.
    exec.go:19: [exec] sudo snap start edgex-device-virtual
    exec.go:93: [stdout] Started.
=== RUN   TestStreamsAndRules/create_stream
    exec.go:19: [exec] edgex-ekuiper.kuiper-cli create stream stream1 '()WITH(FORMAT="JSON",TYPE="edgex")'
=== RUN   TestStreamsAndRules/create_rule_log
    exec.go:19: [exec] edgex-ekuiper.kuiper-cli create rule rule_log '
                                {
                                        "sql":"SELECT * from stream1",
                                        "actions":[
                                                {
                                                        "log":{}
                                                }
                                        ]
                                }'
=== RUN   TestStreamsAndRules/create_rule_edgex_message_bus
    exec.go:19: [exec] edgex-ekuiper.kuiper-cli create rule rule_edgex_message_bus '
                                {
                                   "sql":"SELECT * from stream1",
                                   "actions": [
                                          {
                                                 "edgex": {
                                                        "connectionSelector": "edgex.redisMsgBus",
                                                        "topicPrefix": "edgex/events/device", 
                                                        "messageType": "request",
                                                        "deviceName": "device-test"
                                                 }
                                          }
                                   ]
                                }'
=== CONT  TestStreamsAndRules
    net.go:140: Retry 1/60: Waiting for ports: 59900 (device-virtual)
    net.go:140: Retry 2/60: Waiting for ports: 59900 (device-virtual)
=== RUN   TestStreamsAndRules/query_readings
    readings.go:45: waiting for device-virtual produce readings, current retry count: 1/60
    readings.go:45: waiting for device-virtual produce readings, current retry count: 2/60
    readings.go:45: waiting for device-virtual produce readings, current retry count: 3/60
    readings.go:45: waiting for device-virtual produce readings, current retry count: 4/60
    readings.go:45: waiting for device-virtual produce readings, current retry count: 5/60
    readings.go:45: waiting for device-virtual produce readings, current retry count: 6/60
    readings.go:45: waiting for device-virtual produce readings, current retry count: 7/60
    readings.go:45: waiting for device-virtual produce readings, current retry count: 8/60
    readings.go:45: waiting for device-virtual produce readings, current retry count: 9/60
    readings.go:45: waiting for device-virtual produce readings, current retry count: 10/60
    readings.go:48: device-virtual is producing readings now, readings queried from core-data
=== RUN   TestStreamsAndRules/check_rule_log
    exec.go:19: [exec] sudo journalctl --since "2022-10-24 15:10:37" --no-pager | grep "edgex-ekuiper"|| true
=== RUN   TestStreamsAndRules/check_rule_edgex_message_bus
    net.go:140: Retry 1/60: Waiting for ports: 59900 (device-virtual)
=== CONT  TestStreamsAndRules
    exec.go:19: [exec] sudo snap stop edgex-ekuiper.kuiper
    exec.go:93: [stdout] Stopped.
    exec.go:19: [exec] sudo snap stop edgex-device-virtual
    exec.go:93: [stdout] 2022-10-24T15:18:22+02:00 INFO Waiting for "snap.edgex-device-virtual.device-virtual.service" to stop.
    exec.go:93: [stdout] Stopped.
--- PASS: TestStreamsAndRule [...]

2022-10-24 13:47 UTC, farshidtz approved these changes
I made some corrections in the REAME: https://github.com/canonical/edgex-ekuiper-snap/pull/34/commits/a08194e685f7a992cbf4d3ed4bb20e9a9246e7c1

Otherwise it looks good and all the updated tests pass.
Thank you!

2022-10-24 13:49 UTC, merged