fix(snap): Refactor to avoid conflicts with readonly config provider …
canonical/edgex-ekuiper-snap pull request #51
Opened 2023-03-17 16:03 UTC by MonicaisHer

Changes to incorporate the following fixes:
- https://github.com/canonical/edgex-snap-hooks/pull/83
- https://github.com/canonical/edgex-snap-hooks/pull/82

For testing instructions, please refer to https://github.com/edgexfoundry/device-mqtt-go/pull/535

2023-03-18 04:10 UTC, farshidtz requested changes

2023-03-18 04:10 UTC, farshidtz commented on snap/local/helper-go/install.go
> +	isConnected, err := snapctl.IsConnected(app + "-config").Run()
The identifier of the config interface slot is not kuiperd-config.

2023-03-18 04:10 UTC, farshidtz commented on snap/local/helper-go/main.go
> +const app = "kuiperd"
Having a global variable called `app` is confusing because this snap has two apps.

2023-03-20 09:38 UTC, MonicaisHer commented on snap/local/helper-go/main.go
> +const app = "kuiperd"
It has been updated to `const daemonApp = "kuiperd"`.

2023-03-20 09:39 UTC, MonicaisHer commented
- [ ] Rerun the snap testing once this [PR](https://github.com/canonical/edgex-snap-testing/pull/171) has been merged.

2023-03-20 10:23 UTC, farshidtz requested changes

2023-03-20 10:23 UTC, farshidtz commented on snap/local/bin/source-env-file.sh
> +#!/bin/bash -ex
```suggestion
#!/bin/bash -e
```

I think if xtrace is enabled, the commands will appear in syslogs without the appropriate component name or tag. The reader can't know which application they come from.

2023-03-20 10:23 UTC, farshidtz commented on snap/local/bin/source-env-file.sh
> +ENV_FILE="$SNAP_DATA/config/$SERVICE/res/overrides.env"
```suggestion
ENV_FILE="$SNAP_DATA/config/$SERVICE/overrides.env"
```

2023-03-20 10:31 UTC, farshidtz commented on snap/local/bin/source-env-file.sh
> +ENV_FILE="$SNAP_DATA/config/$SERVICE/res/overrides.env"
Please note that there are no tests for the config options passed to this snap. So the tests pass regardless.

2023-03-21 10:43 UTC, farshidtz approved these changes
Looks good. Thanks

2023-03-21 10:44 UTC, merged