Move env variables to snapcraft and use `$SNAP_INSTANCE_NAME`
canonical/edgex-ekuiper-snap pull request #9
Opened 2022-03-17 15:59 UTC by MonicaisHer

Signed-off-by: Mengyi Wang <mengyi.wang@canonical.com>

2022-03-17 16:22 UTC, farshidtz commented on snap/local/runtime-helpers/bin/setup-redis-credentials
> +		logger --stderr "$SNAP_INSTANCE_NAME:setup-redis-credentials: $ITEM exited with code $EXIT_CODE: $RESPONSE"
Please assign `$SNAP_INSTANCE_NAME:setup-redis-credentials` to a LOG_PREFIX variable and reuse to make your log lines shorter.

2022-03-17 16:39 UTC, farshidtz requested changes

2022-03-17 16:39 UTC, farshidtz commented on snap/local/runtime-helpers/bin/setup-redis-credentials
> -CONNECTIONS_FILE=$SNAP_DATA/etc/connections/connection.yaml
I think it would be good to check that the three env vars are set, to avoid cryptic in the script errors when they aren't.
e.g.
```bash
if [ -z "$VAULT_TOKEN_FILE" ]
then
    echo "VAULT_TOKEN_FILE not set"
    exit 1
fi
```

2022-03-17 16:41 UTC, farshidtz requested changes

2022-03-17 16:41 UTC, farshidtz commented on snap/snapcraft.yaml
> +      CONNECTIONS_FILE: $SNAP_DATA/etc/connections/connection.yaml
`SOURCE_FILE` for sources/edgex.yaml 
`CONNECTION_FILE` (singular) for connections/connection.yaml

2022-03-18 08:51 UTC, MonicaisHer commented on snap/local/runtime-helpers/bin/setup-redis-credentials
> -CONNECTIONS_FILE=$SNAP_DATA/etc/connections/connection.yaml
`if [ -z "$VAULT_TOKEN_FILE" ]` doesn't distinguish between a variable that is unset and a variable that is set to the empty string.

2022-03-18 09:50 UTC, farshidtz commented on snap/local/runtime-helpers/bin/setup-redis-credentials
> -CONNECTIONS_FILE=$SNAP_DATA/etc/connections/connection.yaml
> doesn't distinguish between a variable that is unset and a variable that is set to the empty string

Correct. Do we care to distinguish?

This is the expected behavior:
```bash
$ cat test-var.sh 
#!/bin/bash

if [ -z "$X" ]
then
    echo "X not set"
    exit 1
fi

# not set
$ ./test-var.sh 
X not set

# empty string
$ X="" ./test-var.sh 
X not set

$ X="hi" ./test-var.sh 
$
```

2022-03-18 16:54 UTC, MonicaisHer commented on snap/local/runtime-helpers/bin/setup-redis-credentials
> -CONNECTIONS_FILE=$SNAP_DATA/etc/connections/connection.yaml
This single `if` statement works for me.
When I put multiples vars in a for loop, it treats `unset` as `set`. I really can't figure out why: [related commit](https://github.com/canonical/edgex-ekuiper-snap/pull/9/commits/d85a0b647fd947428a51f084ef754c3899b4b972)

However, I fixed it in the latest commit.

2022-03-19 10:11 UTC, farshidtz commented on snap/local/runtime-helpers/bin/setup-redis-credentials
> -CONNECTIONS_FILE=$SNAP_DATA/etc/connections/connection.yaml
It looks like you fixed it in you last commit.

2022-03-19 10:16 UTC, farshidtz approved these changes

2022-03-19 10:16 UTC, farshidtz commented on snap/local/runtime-helpers/bin/setup-redis-credentials
> +done
This works as expected and it's okay to merge as is. 

I just think it is too complicated for some simple checks. It could have been three `if` statements throwing error if the variable isn't set. No `else` statements needed. Total, that would result in similar number of lines and much more readable code.

2022-03-19 10:17 UTC, farshidtz commented on snap/local/runtime-helpers/bin/setup-redis-credentials
> +done
This is also okay:
```suggestion
for var in VAULT_TOKEN_FILE SOURCE_FILE CONNECTION_FILE ; do
	if [ -z "${!var}" ] ; then
		logger --stderr "$LOG_PREFIX: $var is not set"
		exit 1
	fi
done
```

2022-03-19 10:20 UTC, farshidtz commented
Independent to this PR, I suggest in general to add `set -e` to your scripts so that they exit if one of the commands fail unexpectedly.

2022-03-22 08:55 UTC, farshidtz approved these changes

2022-03-22 08:58 UTC, merged